"""Rename table

Revision ID: 2f3404437eee
Revises: f0f88ed27660
Create Date: 2025-11-11 13:32:06.849074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f3404437eee'
down_revision: Union[str, None] = 'f0f88ed27660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_inai_extracted_json',
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['invoai.tb_inai_mas_vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('return_id'),
    schema='invoai'
    )
    op.create_index(op.f('ix_invoai_tb_inai_extracted_json_return_id'), 'tb_inai_extracted_json', ['return_id'], unique=False, schema='invoai')
    op.drop_index('ix_invoai_tb_inai_return_json_return_id', table_name='tb_inai_return_json', schema='invoai')
    op.drop_table('tb_inai_return_json', schema='invoai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_inai_return_json',
    sa.Column('return_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('extracted_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['invoai.tb_inai_mas_vendor.vendor_id'], name='tb_inai_return_json_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('return_id', name='tb_inai_return_json_pkey'),
    schema='invoai'
    )
    op.create_index('ix_invoai_tb_inai_return_json_return_id', 'tb_inai_return_json', ['return_id'], unique=False, schema='invoai')
    op.drop_index(op.f('ix_invoai_tb_inai_extracted_json_return_id'), table_name='tb_inai_extracted_json', schema='invoai')
    op.drop_table('tb_inai_extracted_json', schema='invoai')
    # ### end Alembic commands ###
