"""init migration

Revision ID: 9ba783341685
Revises: 
Create Date: 2025-11-07 09:19:11.897563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba783341685'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_inai_mas_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_tb_inai_mas_user_user_id'), 'tb_inai_mas_user', ['user_id'], unique=False)
    op.create_table('tb_inai_mas_vendor',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('vendor_name')
    )
    op.create_index(op.f('ix_tb_inai_mas_vendor_vendor_id'), 'tb_inai_mas_vendor', ['vendor_id'], unique=False)
    op.create_table('tb_inai_extraction_details',
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('extraction_name', sa.String(length=50), nullable=False),
    sa.Column('x_min', sa.Integer(), nullable=True),
    sa.Column('x_max', sa.Integer(), nullable=True),
    sa.Column('y_min', sa.Integer(), nullable=True),
    sa.Column('y_max', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['tb_inai_mas_vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('extraction_id')
    )
    op.create_index(op.f('ix_tb_inai_extraction_details_extraction_id'), 'tb_inai_extraction_details', ['extraction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_inai_extraction_details_extraction_id'), table_name='tb_inai_extraction_details')
    op.drop_table('tb_inai_extraction_details')
    op.drop_index(op.f('ix_tb_inai_mas_vendor_vendor_id'), table_name='tb_inai_mas_vendor')
    op.drop_table('tb_inai_mas_vendor')
    op.drop_index(op.f('ix_tb_inai_mas_user_user_id'), table_name='tb_inai_mas_user')
    op.drop_table('tb_inai_mas_user')
    # ### end Alembic commands ###
