"""create all invoai tables

Revision ID: e30de1f6cd35
Revises: 9ba783341685
Create Date: 2025-11-07 09:34:34.030537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e30de1f6cd35'
down_revision: Union[str, None] = '9ba783341685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_inai_mas_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='invoai'
    )
    op.create_index(op.f('ix_invoai_tb_inai_mas_user_user_id'), 'tb_inai_mas_user', ['user_id'], unique=False, schema='invoai')
    op.create_table('tb_inai_mas_vendor',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('vendor_name'),
    schema='invoai'
    )
    op.create_index(op.f('ix_invoai_tb_inai_mas_vendor_vendor_id'), 'tb_inai_mas_vendor', ['vendor_id'], unique=False, schema='invoai')
    op.create_table('tb_inai_extraction_details',
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('extraction_name', sa.String(length=50), nullable=False),
    sa.Column('x_min', sa.Integer(), nullable=True),
    sa.Column('x_max', sa.Integer(), nullable=True),
    sa.Column('y_min', sa.Integer(), nullable=True),
    sa.Column('y_max', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['invoai.tb_inai_mas_vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('extraction_id'),
    schema='invoai'
    )
    op.create_index(op.f('ix_invoai_tb_inai_extraction_details_extraction_id'), 'tb_inai_extraction_details', ['extraction_id'], unique=False, schema='invoai')
    op.create_table('tb_inai_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('logout_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['invoai.tb_inai_mas_user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id'),
    schema='invoai'
    )
    op.create_index(op.f('ix_invoai_tb_inai_log_log_id'), 'tb_inai_log', ['log_id'], unique=False, schema='invoai')
    op.create_table('tb_inai_return_json',
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['invoai.tb_inai_mas_vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('return_id'),
    schema='invoai'
    )
    op.create_index(op.f('ix_invoai_tb_inai_return_json_return_id'), 'tb_inai_return_json', ['return_id'], unique=False, schema='invoai')
    op.drop_index('ix_tb_inai_extraction_details_extraction_id', table_name='tb_inai_extraction_details')
    op.drop_table('tb_inai_extraction_details')
    op.drop_index('ix_tb_inai_mas_vendor_vendor_id', table_name='tb_inai_mas_vendor')
    op.drop_table('tb_inai_mas_vendor')
    op.drop_index('ix_tb_inai_mas_user_user_id', table_name='tb_inai_mas_user')
    op.drop_table('tb_inai_mas_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_inai_mas_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='tb_inai_mas_user_pkey')
    )
    op.create_index('ix_tb_inai_mas_user_user_id', 'tb_inai_mas_user', ['user_id'], unique=False)
    op.create_table('tb_inai_mas_vendor',
    sa.Column('vendor_id', sa.INTEGER(), server_default=sa.text("nextval('tb_inai_mas_vendor_vendor_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vendor_id', name='tb_inai_mas_vendor_pkey'),
    sa.UniqueConstraint('vendor_name', name='tb_inai_mas_vendor_vendor_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_tb_inai_mas_vendor_vendor_id', 'tb_inai_mas_vendor', ['vendor_id'], unique=False)
    op.create_table('tb_inai_extraction_details',
    sa.Column('extraction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('extraction_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('x_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('x_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['tb_inai_mas_vendor.vendor_id'], name='tb_inai_extraction_details_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('extraction_id', name='tb_inai_extraction_details_pkey')
    )
    op.create_index('ix_tb_inai_extraction_details_extraction_id', 'tb_inai_extraction_details', ['extraction_id'], unique=False)
    op.drop_index(op.f('ix_invoai_tb_inai_return_json_return_id'), table_name='tb_inai_return_json', schema='invoai')
    op.drop_table('tb_inai_return_json', schema='invoai')
    op.drop_index(op.f('ix_invoai_tb_inai_log_log_id'), table_name='tb_inai_log', schema='invoai')
    op.drop_table('tb_inai_log', schema='invoai')
    op.drop_index(op.f('ix_invoai_tb_inai_extraction_details_extraction_id'), table_name='tb_inai_extraction_details', schema='invoai')
    op.drop_table('tb_inai_extraction_details', schema='invoai')
    op.drop_index(op.f('ix_invoai_tb_inai_mas_vendor_vendor_id'), table_name='tb_inai_mas_vendor', schema='invoai')
    op.drop_table('tb_inai_mas_vendor', schema='invoai')
    op.drop_index(op.f('ix_invoai_tb_inai_mas_user_user_id'), table_name='tb_inai_mas_user', schema='invoai')
    op.drop_table('tb_inai_mas_user', schema='invoai')
    # ### end Alembic commands ###
