"""Updated Vendor table with add new columns

Revision ID: f0f88ed27660
Revises: e30de1f6cd35
Create Date: 2025-11-11 12:01:46.039817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f88ed27660'
down_revision: Union[str, None] = 'e30de1f6cd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_inai_mas_vendor', sa.Column('updated_by', sa.Integer(), nullable=True), schema='invoai')
    op.add_column('tb_inai_mas_vendor', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True), schema='invoai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_inai_mas_vendor', 'updated_at', schema='invoai')
    op.drop_column('tb_inai_mas_vendor', 'updated_by', schema='invoai')
    # ### end Alembic commands ###
